In [36]:
import pandas as pd

exam_data = {'name':['hongildong','hongeeedong','hongsamdong'],
             'math':[90,80,70],
             'eng':[98,89,95],
             'music':[85,95,100],
             'phys_tra':[100,90,90]}
df = pd.DataFrame(exam_data)
# print(df)

df.index

df.set_index('name',inplace=True)
df.index

df

a = df.loc['hongildong','music']
a

c= df.loc['hongildong',['music','phys_tra']]
c

d = df.iloc[0,[2,3]]
d

e = df.loc['hongildong','music':'phys_tra']
e

f= df.iloc[0,2:]
f

g = df.loc[['hongildong','hongeeedong'],['music','phys_tra']]
g

h = df.iloc[[0,1],[2,3]]
h

i= df.loc['hongildong':'hongeeedong','music':'phys_tra']
i

df

df['kor']=80
df

df.loc[3]=0
df

df.loc[3]=[90,80,70,60,77]
df

df.index
df.index[2]

df = df.reset_index()
df

df.iloc[3,0]='hongsadong'
df

df.set_index('name',inplace=True)
df

             math  eng  music  phys_tra  kor
name
hongildong     90   98     85       100   80
hongeeedong    80   89     95        90   80
hongsamdong    70   95    100        90   80
hongsadong     90   80     70        60   77

In [50]:
exam_data={'name':['stu1','stu2','stu3'],
           'math':[90,80,70],
           'eng':[98,89,95],
           'mus':[85,95,100],
           'phy':[100,90,90]}

df= pd.DataFrame(exam_data)
df

df.index
df.set_index('name',inplace=True)
df

df.iloc[0][3]=80
df

df.loc['stu1']['phy']=90
df

df.loc['stu1','phy']=100
df

df.loc['stu1',['mus','phy']]=50
df

df.loc['stu1',['mus','phy']]=100,100
df


df.reset_index(inplace=True)
df

dff = df.transpose()
dff

dfff =dff.T
dfff

/tmp/ipykernel_3573/2938631426.py:14: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df.iloc[0][3]=80
/tmp/ipykernel_3573/2938631426.py:14: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  df.iloc[0][3]=80
/tmp/ipykernel_3573/2938631426.py:17: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df.loc['stu1']['phy']=90

   name math eng  mus  phy
0  stu1   90  98  100  100
1  stu2   80  89   95   90
2  stu3   70  95  100   90

In [66]:
exam_data={'name':['stu1','stu2','stu3'],
           'math':[90,80,70],
           'eng':[98,89,95],
           'mus':[85,95,100],
           'phy':[100,90,90]}

df= pd.DataFrame(exam_data)

ndf = df.set_index(['name'])
ndf

ndf2 = ndf.set_index('mus')
ndf2

ndf3=ndf.set_index(['math','mus'])   #multiindexing
ndf3

dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9],'c3':[10,11,12],'c4':[13,14,15]}
df = pd.DataFrame(dict_data, index=['r0','r1','r2'])
df

new_index=['r0','r1','r2','r3','r4']
ndf = df.reindex(new_index)
ndf

new_index=['r0','r1','r2','r3','r4']
ndf2 = df.reindex(new_index, fill_value=0)
ndf2

ndf = df.reset_index()
ndf

  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15

In [ ]:
#starts from 3rd book